name: Matrix Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker
        if: runner.os == 'Linux'
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Image
        run: |
          if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then
            docker run ${{ matrix.images }};
          else
            echo "Skipping incompatible Docker image for Windows runner.";
