name: Docker Workflow

on:
  - push
  
jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build 
      run: docker build -t docker.io/ocloo/resume-app:latest .