name: ASCII Workflow

on:
  push:

jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install cowsay
        run: |
          sudo apt-get update
          sudo apt-get install cowsay -y

      - name: Create dragon.txt (if needed)
        run: |
          echo "A dragon is a large, serpentine legendary creature" > dragon.txt

      - name: Search for 'dragon'
        run: |
          grep -i "dragon" dragon.txt
